-- WITH TRIPS as (

-- select
-- RIDE_ID,
-- -- RIDEABLE_TYPE,
-- DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
-- START_STATIO_ID AS START_STATION_ID,
-- END_STATION_ID,
-- MEMBER_CSUAL AS MEMBER_CASUAL,
-- TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

-- from  {{ source('demo', 'bike') }}

-- where RIDE_ID != '"bikeid"' and RIDE_ID != 'bikeid'
-- AND TRY_TO_TIMESTAMP(STARTED_AT, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL
--       AND TRY_TO_TIMESTAMP(ENDED_AT, 'YYYY-MM-DD HH24:MI:SS') IS NOT NULL

-- )

-- select
-- *
-- from TRIPS



WITH TRIPS AS (
    SELECT
        RIDE_ID,
        DATE(TRY_TO_TIMESTAMP(STARTED_AT, 'YYYY-MM-DD HH24:MI:SS.FF3')) AS TRIP_DATE,
        START_STATIO_ID,
        END_STATION_ID,
        MEMBER_CSUAL,
        TIMESTAMPDIFF(
            SECOND,
            TRY_TO_TIMESTAMP(STARTED_AT, 'YYYY-MM-DD HH24:MI:SS.FF3'),
            TRY_TO_TIMESTAMP(ENDED_AT, 'YYYY-MM-DD HH24:MI:SS.FF3')
        ) AS TRIP_DURATION_SECONDS
    FROM {{ ref('stg_bike') }}
    WHERE RIDE_ID NOT IN ('bikeid', '"bikeid"')
      AND TRY_TO_TIMESTAMP(STARTED_AT, 'YYYY-MM-DD HH24:MI:SS.FF3') IS NOT NULL
      AND TRY_TO_TIMESTAMP(ENDED_AT, 'YYYY-MM-DD HH24:MI:SS.FF3') IS NOT NULL
)

SELECT *
FROM TRIPS



